### ISSUE TITLE
Clinic Info

### ISSUE THREAD

**Issue by saifalamkhan373** [wrappid/profile-module#10]
**What is the problem?**
1) The Full name field is taking integer and special character and its showing no alert message
2)Country, State, District, city, landmark, these all field are taking integer value and special character too and its not showing any alert 
3)While clicking the save button, its showing an error alert.

**What is the proposed solution?**

**Comment by techoneel** [comment]
https://github.com/wrappid/profile-module/issues/73 duplicate
