### ISSUE TITLE
enhancement: profile module design enhancements

### ISSUE THREAD

**Issue by saifalamkhan373** [wrappid/profile-module#14]
### Problem

We need to make the UI information architecture look a little more promising.

### Solutions

The design team provides us a basic UI design that could fulfill our requirements.

The design guide is available in figma [here](https://www.figma.com/file/03niFVCaPkzBate9YjPTqn/Rxefy-App?type=design&mode=design&t=XIeBOX74R7ymM4mx-0).

Also shared with you previously.

### Steps to achieve

1. Create a dummy UI in your component with a dummy json schema.
2. Create the business entity following the guide provided [here](https://github.com/wrappid/app-builder-module#how-to-create-a-business-entity-).

**Comment by techoneel** [comment]
will be taken by @anantakumarghosh in https://github.com/wrappid/profile-module/issues/73
