### ISSUE TITLE
DOB field in Profile

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/profile-module#51]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">Describe the bug</strong><br style="box-sizing: border-box;">In the user profile page, in the date of birth field, the error message shown by the input field validator reads "Max age should be 18".<br style="box-sizing: border-box;">Instead it should be "Min age should be 18".</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">To Reproduce</strong><br style="box-sizing: border-box;">Steps to reproduce the behavior:</p><ol dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Log in to the app.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Click on the profile picture.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Click on View Profile.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Click on the Date of Birth input field.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Enter any date which makes the user less than 18 years of age.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Hit Enter.</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">The following error message will show "Max age should be 18".</li></ol><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">Expected behavior</strong><br style="box-sizing: border-box;">The error message should read "Min age should be 18".<br style="box-sizing: border-box;">Date Picker should not allow a date to picked which makes the user less than 18 years of age.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">Screenshots</strong><br style="box-sizing: border-box;">NA</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">Application Info:</strong></p>
Key | Value
-- | --
Frontend URL | http://stageapp.rxefy.com
Frontend Version | 0.7.6
Backend URL | https://stageapi.rxefy.com/apiDocs
Backend Version | 0.7.6

</body>
</html>Describe the bug
In the user profile page, in the date of birth field, the error message shown by the input field validator reads "Max age should be 18".
Instead it should be "Min age should be 18".

To Reproduce

Log in to the app.
Click on the profile picture.
Click on View Profile.
Click on the Date of Birth input field.
Enter any date which makes the user less than 18 years of age.
Hit Enter.
The following error message will show "Max age should be 18".
Expected behavior
The error message should read "Min age should be 18".
Date Picker should not allow a date to picked which makes the user less than 18 years of age.

Screenshots
NA

Application Info:

Key	Value
Frontend URL	http://stageapp.rxefy.com/
Frontend Version	0.7.6
Backend URL	https://stageapi.rxefy.com/apiDocs
Backend Version	0.7.6
Desktop (please complete the following information):

Key	Value
OS	Windows 10
Browser	Mozilla Firefox
Version	111.0.1
Smartphone (please complete the following information):

Key	Value
Device	Realme 6
OS	Android 11
Browser	Google Chrome
Version	94.0.4606.85
Reporter Information:

Key	Value
Name	Aditya Jaiswal
Email	[adityajaiswal094@gmail.com](mailto:adityajaiswal094@gmail.com)
Phone	null
Role	Doctor
Creation Time	07/04/2023 4:00:00 PM

**Comment by techoneel** [comment]
This issue is fixed and deployed
