### ISSUE TITLE
enhancement: cleanup and refactor

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/profile-module#73]
# Description
Code cleanup and refactor if required of the code and DB schemas.

# What problem we're solving?
We are refactoring for the production ready code.

# What is the proposed solution?
- [x] Analyze DB design - if changes required
- [ ] Restructuring the UI & API Routes
- [ ] Fix the Form(s) Validation
- [x] Fix the CRUD API Validation
- [x] Discussion required regarding the application specific code placement - with @techoneel and @samhere17

# Additional notes
Go through all other issues present in module and close if irrelevant or similar.

**Comment by techoneel** [comment]
Please update your overall development closure and testing analysis in detail.

**Comment by anantakumarghosh** [comment]
> Please update your overall development closure and testing analysis in detail.

Will do so after closure.

**Comment by anantakumarghosh** [comment]
Thanks for the updating the description @techoneel , appreciated. :smiley:

**Comment by techoneel** [comment]
> > Please update your overall development closure and testing analysis in detail.
> 
> Will do so after closure.

Daily status update of the issue in progress needs to be shared in comment

**Comment by anantakumarghosh** [comment]
Sure!

**Comment by samhere17** [comment]
This is regarding the below point from the issue description:

> Discussion required regarding the application specific code placement

As discussed earlier, for wrappid, all modules should support module extension, e.g. auth-module (provided by wrappid) should be allowed to be extended in application and may be named "authx" (say). At runtime they should get integrated and "authx" should be served as part of the "auth" module. That's what the vision is.

@techoneel considering the delivery timeline of customer applications, I leave it to your judgement (also discuss @gautamdey), how to do it, when to do it and whether at all to do it now.

**Comment by anantakumarghosh** [comment]
> This is regarding the below point from the issue description:
> 
> > Discussion required regarding the application specific code placement
> 
> As discussed earlier, for wrappid, all modules should support module extension, e.g. auth-module (provided by wrappid) should be allowed to be extended in application and may be named "authx" (say). At runtime they should get integrated and "authx" should be served as part of the "auth" module. That's what the vision is.
> 
> @techoneel considering the delivery timeline of customer applications, I leave it to your judgement (also discuss @gautamdey), how to do it, when to do it and whether at all to do it now.

Alright, thanks for your suggestion

**Comment by anantakumarghosh** [comment]
As discussed with @techoneel , we are deciding to make this repo a template. In future, any application org will be able to create a repository via this template, and also enable them to fetch changes from wrappid.

**Comment by anantakumarghosh** [comment]
after merge of the mentioned PR, repo will be ready for creating other profile-modules via template
